spring:
  datasource:
    url: jdbc:mysql://localhost:3306/investment?createDatabaseIfNotExist=true
    username: root
    password: pedro1995
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
        ddl-auto: update